- hosts: 127.0.0.1
  vars_files:
    - var/database-cluster.yml
  connection: local
  tasks:
    - name: create database security group
      local_action:
        module: ec2_group
        name: database
        description: Security group for Cassandra clusters
        region: eu-west-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 0
            to_port: 65535
            group_name: database
        state: present

    - name: create seed node instances
      local_action:
        module: ec2
        key_name: "{{key_name}}"
        instance_type: "{{node_instance_type}}"
        image: "{{node_ami}}"
        region: eu-west-1
        volumes: "{{ database_node_volumes }}"
        wait: yes
        group: database
        instance_tags:
          Name: database-node
          Seed: yay
          Environment: "{{cluster_environment}}"
        count_tag:
          Name: database-node
          Seed: yay
          Environment: "{{cluster_environment}}"
        exact_count: "{{seed_count}}"
      register: ec2_seeds
      tags:
        - instances

    - name: Wait for SSH on seed machines
      wait_for: host={{ item.public_ip }} delay=15 port=22 state=started
      with_items: ec2_seeds.instances
      when: ec2_seeds.changed
      tags:
        - instances

    - name: add machines to database-seeds group
      add_host: hostname={{ item.public_ip }} groupname=database-seeds
      with_items: ec2_seeds.tagged_instances
      tags:
        - instances

    - name: create database nodes instances
      local_action:
        module: ec2
        key_name: "{{key_name}}"
        instance_type: "{{node_instance_type}}"
        image: "{{node_ami}}"
        region: eu-west-1
        volumes: "{{ database_node_volumes }}"
        wait: yes
        group: database
        instance_tags:
          Name: database-node
          Seed: nay
          Environment: "{{cluster_environment}}"
        count_tag:
          Name: database-node
          Seed: nay
          Environment: "{{cluster_environment}}"
        exact_count: "{{node_count}}"
      register: ec2_nodes
      tags:
        - instances

    - name: Wait for SSH on node machines
      wait_for: host={{ item.public_ip }} delay=15 port=22 state=started
      with_items: ec2_nodes.instances
      when: ec2_nodes.changed
      tags:
        - instances

    - name: add database nodes to nodes group
      add_host: hostname={{ item.public_ip }} groupname=database-nodes
      with_items: ec2_nodes.tagged_instances
      tags:
        - instances
